"""Partition connectivity follows resolved dynamics, not network membership."""

from __future__ import annotations

import numpy as np
import pytest

from quchip import (
    Capacitive,
    Chip,
    CoherentInput,
    CollapseChannel,
    Coupling,
    Exact,
    OutputAmplitude,
    PortNetwork,
    QuantumSequence,
    RWA,
    Resonator,
    Square,
)
from quchip.results.partitioned import PartitionedSimulationResult


class _NoisyCapacitive(Capacitive):
    def dissipation(self, a, b, p):
        """Declare a collective edge-loss channel for partition coverage."""
        return (CollapseChannel(a.charge * b.charge, 0.0025, "edge_loss"),)


def test_cascade_generated_hamiltonian_connects_partitions() -> None:
    """A Hamiltonian generated by series composition keeps both devices joint."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    network = PortNetwork(label="cascade")
    first_port = network.port("a_port", target=first, rate=0.02)
    second_port = network.port("b_port", target=second, rate=0.03)
    network.cascade(first_port, second_port)
    network.expose(
        "feedline",
        input=first_port.input,
        output=second_port.output,
    )
    chip = Chip([first, second], port_network=network)

    assert chip.resolve().dynamical_supports == (("a", "b"),)
    assert chip.partition().is_trivial


def test_passive_scattering_does_not_connect_independent_ports() -> None:
    """A passive field-basis rotation does not merge independent subsystems."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    network = PortNetwork(scattering=np.asarray([[0.0, 1.0], [1.0, 0.0]]), label="swap")
    network.port("a_port", target=first, rate=0.02)
    network.port("b_port", target=second, rate=0.03)
    chip = Chip([first, second], port_network=network)

    assert chip.resolve().dynamical_supports == ()
    assert len(chip.partition()) == 2


def test_active_network_with_an_extra_device_stays_joint() -> None:
    """An active network is not partially sliced while graph splitting is unsupported."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    spectator = Resonator(freq=6.0, levels=2, label="c")
    network = PortNetwork(label="cascade")
    first_port = network.port("a_port", target=first, rate=0.02)
    second_port = network.port("b_port", target=second, rate=0.03)
    network.cascade(first_port, second_port)
    network.expose("feedline", input=first_port.input, output=second_port.output)
    chip = Chip([first, second, spectator], port_network=network)

    assert chip.resolve().dynamical_supports == (("a", "b"),)
    assert chip.partition().is_trivial
    assert "generated Hamiltonian" in chip.partition().notes[0]


def test_coupling_dropped_by_rwa_does_not_connect_resolved_partitions() -> None:
    """Partition connectivity follows retained resolved bands rather than authored edges."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    longitudinal_sideband = Coupling(
        first,
        second,
        g=0.02,
        op_a=lambda device: device.lowering_operator() + device.raising_operator(),
        op_b=lambda device: device.number_operator(),
        label="sideband",
    )

    rwa_chip = Chip([first, second], [longitudinal_sideband], approximation=RWA())
    exact_chip = Chip(
        [first.copy(), second.copy()],
        [
            Coupling(
                "a",
                "b",
                g=0.02,
                op_a=lambda device: device.lowering_operator() + device.raising_operator(),
                op_b=lambda device: device.number_operator(),
                label="sideband",
            )
        ],
        approximation=Exact(),
    )

    with pytest.warns(UserWarning, match="vanishes entirely"):
        rwa_resolved = rwa_chip.resolve()
    assert rwa_resolved.dynamical_supports == ()
    assert len(rwa_chip.partition()) == 2
    assert exact_chip.resolve().dynamical_supports == (("a", "b"),)
    assert exact_chip.partition().is_trivial


def test_concrete_zero_exact_coupling_does_not_connect_partitions() -> None:
    """A concretely vanishing exact Hamiltonian edge has no dynamical support."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    chip = Chip([first, second], [Capacitive(first, second, g=0.0)], approximation=Exact())

    assert chip.resolve().dynamical_supports == ()
    assert len(chip.partition()) == 2


def test_coupling_owned_collapse_channel_connects_partitions() -> None:
    """A collective Lindblad channel survives even when its static edge vanishes."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    coupling = _NoisyCapacitive(first, second, g=0.0, label="lossy_edge")
    chip = Chip([first, second], [coupling], approximation=Exact())

    assert chip.resolve().dynamical_supports == (("a", "b"),)
    assert chip.partition().is_trivial


def test_field_io_declines_component_solve_but_keeps_automatic_simulation() -> None:
    """Field I/O retains the complete external reference plane on a joint solve."""
    first = Resonator(freq=5.0, levels=2, label="a")
    second = Resonator(freq=5.4, levels=2, label="b")
    network = PortNetwork(scattering=np.asarray([[0.0, 1.0], [1.0, 0.0]]), label="swap")
    network.port("left", target=first, rate=0.02)
    network.port("right", target=second, rate=0.03)
    chip = Chip([first, second], port_network=network, frame={"a": 5.0, "b": 5.4})
    sequence = QuantumSequence(chip)
    sequence.schedule(
        CoherentInput("left"),
        envelope=Square(duration=0.2, amplitude=0.01),
    )

    result = sequence.simulate(
        tlist=np.linspace(0.0, 0.2, 3),
        e_ops={"right_out": OutputAmplitude("right")},
    )

    assert not isinstance(result, PartitionedSimulationResult)
    assert result.expect("right_out").shape == (3,)
